@baseUrl = http://localhost:3333/api

GET {{baseUrl}} HTTP/1.1

###

# @name signup
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email": "tuanhien.4dev@test.com",
  "password": "Tu4nhi3nloveyou!",
  "name": "Tuan Hien"
}

###

# @name signin
POST {{baseUrl}}/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "tuanhien.4dev@test.com",
  "password": "Tu4nhi3nloveyou!"
}

###

@authToken = {{signin.response.body.access_token}}

# @name me
GET {{baseUrl}}/auth/me HTTP/1.1
Authorization: Bearer {{authToken}}